# -*- coding: utf-8 -*-

# DB 연결정보
stock_conn:
    stock_ip: "139.150.75.140"
    stock_port: 3306
    stock_db: "stock"
    stock_user: "stock"
    stock_pswd: "stock0601"
    # 컬럼 순서 지정. 소스와 동일해야 함
    stock_columns:
        - "STC_CD"
        - "DT"
        - "TM"
        - "NOW_PRC"
        - "SELL_PRC"
        - "BUY_PRC"

# 종목코드
jongmok_code: "122630"

# 데몬 수행 시간
run_day:
    - "090000"
    - "183800"

# 해당 데몬 수행 분. 해당하는 분에만 작업을 시작함
run_minute:
    - "0000"
    - "5959"

# 긁어오는 간격 초
term_seconds: 1    

# 시뮬레이션
simulation:
    seed_money: 500000
    first_price: 123456
    list_gap:
        # 매수갭, 매도갭, 손절갭
        - [100,40,20]
        - [90,50,30]
        - [80,30,15]